name: mind_me
description: A flutter note board app.

publish_to: 'none'

version: 1.0.1+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  carbon_icons: ^0.0.1+2
  cupertino_icons: ^1.0.2
  day_night_time_picker: ^1.0.2
  extended_masked_text: ^2.2.0
  flutter_local_notifications: ^5.0.0+4
  flutter_mobx: ^2.0.0
  flutter_native_timezone: ^1.0.10
  flutter_svg: ^0.22.0
  get: ^4.1.4
  intl: ^0.17.0
  local_auth: ^1.1.5
  logger: ^1.0.0
  mobx: ^2.0.1
  package_info: ^2.0.0
  path_provider: ^2.0.1
  reorderables: ^0.4.1
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0
  sqflite: ^2.0.0+3
  timezone: ^0.7.0
  url_launcher: ^6.0.3
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  flutter_launcher_icons: ^0.9.0
  mobx_codegen: ^2.0.1+3
  flutter_native_splash: ^1.1.8+4

flutter_icons:
  ios: true
  android: true
  image_path: 'assets/images/brand/icon.png'
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: 'assets/images/brand/foreground.png'

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/brand/splash.png"
  ios: false
  web: false
  android: true
  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see 
  # https://developer.android.com/reference/android/view/Gravity): bottom, center, 
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  android_gravity: fill_horizontal

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/brand/
    - assets/images/
  fonts:
    - family: Chalkboard SE
      fonts:
        - asset: assets/fonts/chalkboard_se.otf
